export const products = [
  {
    id: 1,
    name: "Hamburguesa Clásica",
    description: "Hamburguesa con carne de res, lechuga, tomate, queso y pan artesanal.",
    price: 8.99,
    status: "activo",
    createdAt: "2024-02-02T10:30:00",
  },
  {
    id: 2,
    name: "Pizza Margarita",
    description: "Pizza con base de salsa de tomate, mozzarella fresca y albahaca.",
    price: 12.99,
    status: "activo",
    createdAt: "2024-02-01T14:45:00",
  },
  {
    id: 3,
    name: "Tacos al Pastor",
    description: "Tacos de cerdo marinados con piña, cilantro, cebolla y salsa.",
    price: 7.50,
    status: "activo",
    createdAt: "2024-01-28T09:00:00",
  },
  {
    id: 4,
    name: "Ensalada César",
    description: "Lechuga romana, crutones, queso parmesano y aderezo César casero.",
    price: 9.50,
    status: "inactivo",
    createdAt: "2024-01-25T18:20:00",
  },
  {
    id: 5,
    name: "Sushi Roll Philadelphia",
    description: "Roll con salmón, queso crema y aguacate, cubierto con ajonjolí.",
    price: 11.99,
    status: "activo",
    createdAt: "2024-01-20T16:10:00",
  },
  {
    id: 6,
    name: "Lasagna Bolognesa",
    description: "Capas de pasta con salsa bolognesa, bechamel y queso gratinado.",
    price: 13.99,
    status: "activo",
    createdAt: "2024-01-15T11:55:00",
  },
  {
    id: 7,
    name: "Hot Dog Clásico",
    description: "Pan suave con salchicha de res, cebolla, mostaza y ketchup.",
    price: 5.99,
    status: "inactivo",
    createdAt: "2024-01-10T08:40:00",
  },
  {
    id: 8,
    name: "Papas Fritas",
    description: "Papas fritas crujientes servidas con salsa de queso cheddar.",
    price: 4.99,
    status: "activo",
    createdAt: "2024-01-05T13:25:00",
  },
  {
    id: 9,
    name: "Pollo a la Parrilla",
    description: "Pechuga de pollo a la parrilla con guarnición de vegetales al vapor.",
    price: 14.50,
    status: "activo",
    createdAt: "2023-12-30T20:15:00",
  },
  {
    id: 10,
    name: "Tarta de Chocolate",
    description: "Postre de chocolate con base de galleta y crema batida.",
    price: 6.99,
    status: "activo",
    createdAt: "2023-12-20T07:35:00",
  },
  {
    id: 11,
    name: "Flan de Caramelo",
    description: "Flan casero con caramelo líquido y textura suave.",
    price: 5.50,
    status: "activo",
    createdAt: "2023-12-15T10:45:00",
  },
  {
    id: 12,
    name: "Helado de Vainilla",
    description: "Helado cremoso de vainilla natural con chispas de chocolate.",
    price: 4.50,
    status: "inactivo",
    createdAt: "2023-12-10T14:20:00",
  },
  {
    id: 13,
    name: "Café Espresso",
    description: "Café espresso fuerte, preparado con granos 100% arábica.",
    price: 2.99,
    status: "activo",
    createdAt: "2023-12-05T08:10:00",
  },
  {
    id: 14,
    name: "Jugo de Naranja Natural",
    description: "Jugo de naranja recién exprimido, sin azúcar añadida.",
    price: 3.99,
    status: "activo",
    createdAt: "2023-12-02T09:00:00",
  },
  {
    id: 15,
    name: "Limonada Casera",
    description: "Bebida refrescante con jugo de limón natural y menta.",
    price: 3.50,
    status: "activo",
    createdAt: "2023-12-01T11:30:00",
  },
  {
    id: 16,
    name: "Margarita Clásica",
    description: "Cóctel con tequila, jugo de limón y licor de naranja.",
    price: 7.99,
    status: "activo",
    createdAt: "2023-11-28T20:15:00",
  },
  {
    id: 17,
    name: "Mojito",
    description: "Bebida cubana con ron, hierbabuena, lima y soda.",
    price: 8.50,
    status: "activo",
    createdAt: "2023-11-25T17:45:00",
  },
  {
    id: 18,
    name: "Cerveza Artesanal IPA",
    description: "Cerveza artesanal con notas cítricas y amargor equilibrado.",
    price: 6.50,
    status: "activo",
    createdAt: "2023-11-20T19:30:00",
  },
  {
    id: 19,
    name: "Vino Tinto Cabernet Sauvignon",
    description: "Vino tinto con notas frutales y taninos equilibrados.",
    price: 15.99,
    status: "activo",
    createdAt: "2023-11-15T22:10:00",
  },
  {
    id: 20,
    name: "Agua Mineral",
    description: "Botella de agua mineral natural sin gas.",
    price: 1.99,
    status: "activo",
    createdAt: "2023-11-10T12:00:00",
  }
];
